In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("../data/brunch/session.parquet")

In [3]:
import json
from tqdm import tqdm

with open("../data/dictionary.json") as fp:
    dictionary = json.load(fp)
    
def make_label(x):
    session = x["history"]
    session = [dictionary[elem] for elem in session if elem in dictionary]
    x["session"] = session
    return x

tqdm.pandas()
df = df.progress_apply(make_label, axis=1)

In [ ]:
def make_mask(x):
    session_length = len(x["session"])
    # generating session mask
    session_mask = [1.0] * (session_length - 1)
    session_mask = [0.0] + session_mask
    # generating user mask
    user_mask = [0.0] * (session_length - 1)
    user_mask = user_mask + [1.0]
    x["session_mask"] = session_mask
    x["user_mask"] = user_mask
    return x

df = df.progress_apply(make_mask, axis=1)

In [5]:
#000127ad0f1981cae1292efdb228f0e9
df_train = pd.read_parquet("../data/train.parquet")


Empty DataFrame
Columns: [id, history, timestamp, session, session_mask, user_mask]
Index: []

In [16]:
sample = df_train[df_train.id == "#000549d84169355d490b029755f99381"]

In [17]:
session_mask = sample["session_mask"].values

In [18]:
session_mask

array([array([0.]), array([0.]), array([0., 1.]), array([0.]),
       array([0.]), array([0., 1., 1., 1., 1.]), array([0.]), array([0.]),
       array([0.]), array([0., 1., 1.]), array([0.]), array([0.]),
       array([0., 1., 1., 1., 1., 1., 1., 1., 1.])], dtype=object)

In [15]:
import numpy as np

elements = [elem for elem in session_mask]
array = np.concatenate(elements, axis=None)
array

array([0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 1.])

In [19]:
sample

id  \
2043951  #000549d84169355d490b029755f99381   
2072078  #000549d84169355d490b029755f99381   
2121999  #000549d84169355d490b029755f99381   
2131113  #000549d84169355d490b029755f99381   
2148534  #000549d84169355d490b029755f99381   
2199073  #000549d84169355d490b029755f99381   
2206399  #000549d84169355d490b029755f99381   
2290100  #000549d84169355d490b029755f99381   
2338774  #000549d84169355d490b029755f99381   
2479535  #000549d84169355d490b029755f99381   
2534920  #000549d84169355d490b029755f99381   
2565626  #000549d84169355d490b029755f99381   
3241417  #000549d84169355d490b029755f99381   

                                                   history  \
2043951                                    [@cherry3333_1]   
2072078                                    [@cherry3333_2]   
2121999        [@nareun_134, @cherry3333_2, @cherry3333_1]   
2131113                                    [@cherry3333_3]   
2148534                                    [@cherry3333_4]   
2199073  [@cherry3333_4, @cherry3333_3, @cherry3333_2, ...   
2206399                                    [@cherry3333_5]   
2290100                                    [@cherry3333_6]   
2338774                                    [@cherry3333_7]   
2479535      [@cherry3333_7, @cherry3333_5, @cherry3333_6]   
2534920                                      [@brunch_148]   
2565626                                      [@brunch_149]   
3241417  [@cherry3333_8, @cherry3333_7, @cherry3333_6, ...   

                  timestamp  \
2043951 2019-01-03 11:00:00   
2072078 2019-01-04 12:00:00   
2121999 2019-01-06 16:00:00   
2131113 2019-01-06 23:00:00   
2148534 2019-01-07 16:00:00   
2199073 2019-01-09 15:00:00   
2206399 2019-01-09 21:00:00   
2290100 2019-01-13 11:00:00   
2338774 2019-01-15 01:00:00   
2479535 2019-01-20 16:00:00   
2534920 2019-01-22 18:00:00   
2565626 2019-01-23 20:00:00   
3241417 2019-02-19 05:00:00   

                                                   session  \
2043951                                           [134697]   
2072078                                           [430286]   
2121999                                   [430286, 134697]   
2131113                                           [206046]   
2148534                                           [594840]   
2199073           [594840, 206046, 430286, 134697, 594840]   
2206399                                           [134516]   
2290100                                           [375092]   
2338774                                            [14087]   
2479535                            [14087, 134516, 375092]   
2534920                                           [539383]   
2565626                                           [420070]   
3241417  [122657, 14087, 375092, 14087, 122657, 206046,...   

                                          session_mask  \
2043951                                          [0.0]   
2072078                                          [0.0]   
2121999                                     [0.0, 1.0]   
2131113                                          [0.0]   
2148534                                          [0.0]   
2199073                      [0.0, 1.0, 1.0, 1.0, 1.0]   
2206399                                          [0.0]   
2290100                                          [0.0]   
2338774                                          [0.0]   
2479535                                [0.0, 1.0, 1.0]   
2534920                                          [0.0]   
2565626                                          [0.0]   
3241417  [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]   

                                             user_mask  
2043951                                          [1.0]  
2072078                                          [1.0]  
2121999                                     [0.0, 1.0]  
2131113                                          [1.0]  
2148534                                          [1.0]  
2199073                      [0.0, 0.0, 0.0, 0.0, 1.0]  
2206399   